pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/sampath-id/docker-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d --name my-container my-app'
            }
        }
    }
}
